// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMeCMsaMJyoZeK2mcXQBqzCD1hkoSnJoI',
    appId: '1:683977170445:web:2791a53fcb01e07380bf44',
    messagingSenderId: '683977170445',
    projectId: 'chat-5f886',
    authDomain: 'chat-5f886.firebaseapp.com',
    storageBucket: 'chat-5f886.appspot.com',
    measurementId: 'G-1J8RWDRT34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp4KmM1VhTGTdkfxdD-ct6yaoVzUL60bk',
    appId: '1:683977170445:android:13b9b8adabfe5b4380bf44',
    messagingSenderId: '683977170445',
    projectId: 'chat-5f886',
    storageBucket: 'chat-5f886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACAxk7vbjGWFMLNgsObR1sCzAefUZIWq8',
    appId: '1:683977170445:ios:232de5f1a1d0b6f780bf44',
    messagingSenderId: '683977170445',
    projectId: 'chat-5f886',
    storageBucket: 'chat-5f886.appspot.com',
    iosClientId: '683977170445-2v371g64bdt9ju4u5rv0jeqncrff0bi2.apps.googleusercontent.com',
    iosBundleId: 'com.smartsolution.chat',
  );
}
